jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Check issue actor
      uses: fluttercandies/no-free-usage-action@v1.0.1
      with:
        forked: --no-forked
        token: ${{ secrets.GITHUB_TOKEN }}
        words: "To support our project, please file the issue after you starred the\
          \ repo. Thanks! \U0001F642"
name: No Free usage issue checker
on:
  repository_dispatch:
    types: trigger-ga___issue_check.yml
